### PR TITLE
Update to v2.6.1

### PR DESCRIPTION
**Pull request by Anthchirp**
update recipe and add myself as maintainer

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
This has been failing for quite a while. Does it build and test successfully upstream?

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
Upstream can successfully build it, however our recipes are quite a bit out of date.

**Comment by Anthchirp** [comment]
Upstream is now on version 3, so the information content in this PR is likely very low.

**Pull request closed without merging**
