### PR TITLE
HELICS v2.1.1 feedstock update

### PR DESCRIPTION
**Pull request by nightlark**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nightlark** [comment]
git_url needs to get used to properly fetch the submodules -- the GitHub archive for tagged releases have the code for git submodules and isn't a valid git repository.

**Comment by nightlark** [comment]
@conda-forge-admin please rerender

**Comment by nightlark** [comment]
@conda-forge/core what does the error posted by the bot mean?

**Comment by dnadeau4** [comment]
@nightlark You already use `git_url` and `git-rev` which checkouts the right version of the submodules.   It seems that is the way to go on `conda-forge`.
https://github.com/conda-forge/xgboost-feedstock/issues/22

**Pull request closed without merging**
