### PR TITLE
Add win build

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
Let's see, I'm tying to avoid to use features here, but I think if we skip it for just python 2 it will solve

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by kdheepak** [comment]
Great!

**Comment by kdheepak** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotrevisani** [comment]
it seems the bot is kind slow today, or it's not working. I will rerender that by hand

**Comment by kdheepak** [comment]
Tests have passed! Should I merge?

**Comment by marcelotrevisani** [comment]
Yes, sure, go ahead :)

**Comment by kdheepak** [comment]
Thanks for adding Windows support! 

Any suggestions on what I should do if I want Python 2 support too? I am trying to [build the same](https://github.com/kdheepak/helics-conda) on [my own channel](https://anaconda.org/kdheepak/helics/) but it is still failing on [Python 2 builds](https://ci.appveyor.com/project/kdheepak/helics-conda/build/13/job/wpnkyva2okvj1hr6#L625) because it is not able to find boost. Python 3 builds are passing. Any immediate thoughts come to mind? I'll post this on gitter if the [latest build](https://ci.appveyor.com/project/kdheepak/helics-conda/build/19/job/vvkv1lyrr2a63cfm) fails.

**Comment by marcelotrevisani** [comment]
Hi @kdheepak yes, I think I will do the same here
Just put a selector in ``skip: true  # [vc <14]``

Sorry for delay, I just saw you message right now

**Comment by marcelotrevisani** [comment]
Could you send me the error?

**Pull request merged**
